In [1]:
import pandas as pd
from datetime import datetime

In [2]:
root_cause_results = {
    "Online Retail II": {
        "Quantity Change": 83.62,
        "Order Change": 16.38
    },
    "Instacart": {
        "Orders": 93.16,
        "Products": 6.84
    }
}

causal_results = {
    "Online Retail II": {
        "ATE": 0.010647,
        "Treatment": "Quantity Change",
        "Outcome": "Revenue Change"
    },
    "Instacart": {
        "ATE": 0.006417,
        "Treatment": "Orders",
        "Outcome": "Reorder Rate"
    }
}

counterfactual_results = {
    "+5% Quantity": 0.003097,
    "+10% Quantity": 0.006193,
    "+20% Quantity": 0.012387,
    "+50% Quantity": 0.030967
}

print("ADIF Evidence Loaded")

ADIF Evidence Loaded

In [3]:
executive_summary = f"""
ADIF Executive Decision Report

Generated: {datetime.now()}

Summary:

The ADIF framework analyzed two large-scale retail datasets
containing more than 33 million purchase events.

Root Cause Discovery identified:

• Quantity Change as the dominant revenue driver
  in Online Retail II (83.62%).

• Orders as the dominant reorder driver
  in Instacart (93.16%).

Causal Inference confirmed positive causal effects:

• Quantity Change → Revenue Change
  ATE = 0.010647

• Orders → Reorder Rate
  ATE = 0.006417

Counterfactual analysis demonstrated that
increasing Quantity Change by 50%
produces the highest expected revenue impact.

The evidence indicates that customer purchasing
behavior is the primary mechanism driving
business performance across both datasets.
"""

print(executive_summary)

ADIF Executive Decision Report

Generated: 2026-06-09 21:17:29.896943

Summary:

The ADIF framework analyzed two large-scale retail datasets
containing more than 33 million purchase events.

Root Cause Discovery identified:

• Quantity Change as the dominant revenue driver
  in Online Retail II (83.62%).

• Orders as the dominant reorder driver
  in Instacart (93.16%).

Causal Inference confirmed positive causal effects:

• Quantity Change → Revenue Change
  ATE = 0.010647

• Orders → Reorder Rate
  ATE = 0.006417

Counterfactual analysis demonstrated that
increasing Quantity Change by 50%
produces the highest expected revenue impact.

The evidence indicates that customer purchasing
behavior is the primary mechanism driving
business performance across both datasets.

In [4]:
recommendations = pd.DataFrame({

    "Recommendation":[

        "Increase customer purchase volume",

        "Promote bundle offers and cross-selling",

        "Increase customer order frequency",

        "Monitor KPI drivers continuously",

        "Use causal validation before strategic interventions"

    ],

    "Priority":[

        "High",
        "High",
        "High",
        "Medium",
        "Medium"

    ],

    "Justification":[

        "Strongest revenue driver",

        "Improves quantity purchased",

        "Strongest reorder driver",

        "Early detection of KPI shifts",

        "Avoid correlation-based decisions"

    ]
})

recommendations

,Recommendation,Priority,Justification
0,Increase customer purchase volume,High,Strongest revenue driver
1,Promote bundle offers and cross-selling,High,Improves quantity purchased
2,Increase customer order frequency,High,Strongest reorder driver
3,Monitor KPI drivers continuously,Medium,Early detection of KPI shifts
4,Use causal validation before strategic interve...,Medium,Avoid correlation-based decisions

In [5]:
management_report = f"""
==============================
ADIF MANAGEMENT REPORT
==============================

KEY FINDINGS

1. Quantity Change is the strongest
revenue driver in Online Retail II.

2. Orders are the strongest driver
of customer reorder behavior in Instacart.

3. Causal analysis confirms that
both relationships are causally significant.

4. Counterfactual analysis indicates
that interventions targeting purchasing
volume can improve business outcomes.

STRATEGIC ACTIONS

• Increase basket size.

• Improve customer retention.

• Increase repeat purchase frequency.

• Prioritize initiatives affecting
customer purchasing behavior.

• Validate major decisions using
causal analysis.

OVERALL CONCLUSION

The ADIF framework successfully combines
root cause discovery, causal inference,
counterfactual reasoning, and decision
intelligence to generate actionable
business recommendations.
"""

print(management_report)

==============================
ADIF MANAGEMENT REPORT
==============================

KEY FINDINGS

1. Quantity Change is the strongest
revenue driver in Online Retail II.

2. Orders are the strongest driver
of customer reorder behavior in Instacart.

3. Causal analysis confirms that
both relationships are causally significant.

4. Counterfactual analysis indicates
that interventions targeting purchasing
volume can improve business outcomes.

STRATEGIC ACTIONS

• Increase basket size.

• Improve customer retention.

• Increase repeat purchase frequency.

• Prioritize initiatives affecting
customer purchasing behavior.

• Validate major decisions using
causal analysis.

OVERALL CONCLUSION

The ADIF framework successfully combines
root cause discovery, causal inference,
counterfactual reasoning, and decision
intelligence to generate actionable
business recommendations.

In [6]:
with open(
    "../results/executive_summary.txt",
    "w",
    encoding="utf-8"
) as f:
    f.write(executive_summary)

with open(
    "../results/llm_decision_report.txt",
    "w",
    encoding="utf-8"
) as f:
    f.write(management_report)

recommendations.to_csv(
    "../results/tables/recommendations.csv",
    index=False
)

print("All Decision Intelligence Outputs Saved")

All Decision Intelligence Outputs Saved

In [7]:
import pandas as pd

components = pd.DataFrame({

    "Layer":[
        "Data Intelligence",
        "Root Cause Discovery",
        "Causal Discovery",
        "Causal Inference",
        "Counterfactual Intelligence",
        "Decision Intelligence"
    ],

    "Status":[
        "Implemented",
        "Implemented",
        "Implemented",
        "Implemented",
        "Implemented",
        "Implemented"
    ]

})

components

                         Layer       Status
0            Data Intelligence  Implemented
1         Root Cause Discovery  Implemented
2             Causal Discovery  Implemented
3             Causal Inference  Implemented
4  Counterfactual Intelligence  Implemented
5        Decision Intelligence  Implemented

In [8]:
components.to_csv(
    "../results/tables/adif_components.csv",
    index=False
)

In [9]:
pip install ollama

Requirement already satisfied: ollama in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.6.2)
Requirement already satisfied: httpx>=0.27 in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from ollama) (2.11.7)
Requirement already satisfied: anyio in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx>=0.27->ollama) (4.4.0)
Requirement already satisfied: certifi in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx>=0.27->ollama) (2026.1.4)
Requirement already satisfied: httpcore==1.* in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpx>=0.27->ollama) (2.10)
Requirement already satisfied: h11>=0.16 in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic>=2.9->ollama) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic>=2.9->ollama) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pydantic>=2.9->ollama) (0.4.1)
Requirement already satisfied: sniffio>=1.1 in c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages (from anyio->httpx>=0.27->ollama) (1.3.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ympy (c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ympy (c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ympy (c:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
from ollama import chat

In [15]:
import os
print(os.listdir("../results/tables"))

['adif_components.csv', 'final_results.csv', 'model_comparison.csv', 'recommendations.csv', 'root_cause_importance.csv', 'sensitivity_analysis.csv']

In [16]:
import pandas as pd

importance = pd.read_csv(
    "../results/tables/root_cause_importance.csv"
)

sensitivity = pd.read_csv(
    "../results/tables/sensitivity_analysis.csv"
)

print(importance)
print(sensitivity)

           Feature  Importance
0  Customer_Change    0.535396
1  Quantity_Change    0.347384
2     Order_Change    0.117219
   Increase    Impact
0         5  0.003097
1        10  0.006193
2        20  0.012387
3        50  0.030967

In [17]:
ate_value = 0.010647

In [31]:
prompt = f"""
You are an enterprise decision intelligence assistant.

ONLY use the facts provided below.

Do NOT invent numbers.
Do NOT estimate revenue values.
Do NOT make assumptions.

FACTS

Root Cause Analysis:

{importance.to_string(index=False)}

Average Treatment Effect:
{ate_value}

Counterfactual Analysis:

{sensitivity.to_string(index=False)}

TASK

Generate:

1. Executive Summary
2. Key Findings
3. Strategic Recommendations

Every recommendation must explicitly reference the evidence above.

If information is unavailable, state:
'Not available from current analysis.'
"""

In [32]:
from ollama import chat

response = chat(
    model="llama3.1:8b",
    messages=[
        {
            "role": "user",
            "content": prompt
        }
    ]
)

report = response["message"]["content"]

print(report)

Based on the provided facts, I'll generate the requested outputs.

**Executive Summary**

Our analysis indicates that customer changes have the greatest impact on the business outcome, with an importance score of 0.535396. Conversely, order changes have the lowest impact, with a score of 0.117219. The average treatment effect is approximately 0.010647. We also found that increasing the impact by a certain percentage yields specific effects, ranging from 0.003097 (5% increase) to 0.030967 (50% increase).

**Key Findings**

1. Customer changes have the most significant impact on the business outcome, with an importance score of 0.535396.
2. The average treatment effect is approximately 0.010647.
3. Increasing the impact by a certain percentage yields specific effects:
	* A 5% increase results in an impact of 0.003097.
	* A 10% increase results in an impact of 0.006193.
	* A 20% increase results in an impact of 0.012387.
	* A 50% increase results in an impact of 0.030967.

**Strategic Recommendations**

1. **Prioritize efforts to address customer changes**: Given the high importance score (0.535396), it is essential to focus on understanding and addressing the root causes of customer changes to maximize their positive effect.
2. **Investigate further analysis for Order Changes**: Although order changes have the lowest impact, we cannot determine if there are opportunities to increase their effectiveness without further analysis (Not available from current analysis).
3. **Targeted interventions for specific percentage increases in impact**:
	* Consider implementing a 5% increase in some areas where a small boost could have a significant effect (0.003097).
	* For larger impacts, aim for the 20% or 50% increase targets, which would yield effects of 0.012387 and 0.030967, respectively.

In [20]:
with open(
    "../results/llm_generated_report.txt",
    "w",
    encoding="utf-8"
) as f:
    f.write(report)

print("Saved")

Saved

In [22]:
import os
import sys

os.environ.pop("MPLBACKEND", None)

mods = [m for m in list(sys.modules.keys())
        if m.startswith("matplotlib")]

for m in mods:
    del sys.modules[m]

print("Matplotlib reset")

Matplotlib reset

In [23]:
import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt

print("Success")

Success

In [24]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12,10))
plt.axis("off")

plt.text(
    0,
    1,
    report,
    fontsize=10,
    va="top",
    wrap=True
)

plt.savefig(
    "../results/figures/llm_recommendation_output.png",
    dpi=300,
    bbox_inches="tight"
)

plt.close()

print("Figure Saved")

Figure Saved

In [25]:
with open(
    "../results/llm_decision_report.txt",
    "w",
    encoding="utf-8"
) as f:
    f.write(report)

print("LLM Report Saved")

LLM Report Saved

In [26]:
recommendations = pd.DataFrame({

    "Recommendation":[
        "Increase purchase volume",
        "Improve retention",
        "Increase order frequency",
        "Monitor KPI drivers",
        "Use causal validation"
    ],

    "Priority":[
        "High",
        "High",
        "High",
        "Medium",
        "Medium"
    ]
})

recommendations

             Recommendation Priority
0  Increase purchase volume     High
1         Improve retention     High
2  Increase order frequency     High
3       Monitor KPI drivers   Medium
4     Use causal validation   Medium

In [27]:
recommendations.to_csv(
    "../results/tables/recommendations.csv",
    index=False
)

print("Recommendations Saved")

Recommendations Saved

In [28]:
components = pd.DataFrame({

    "Layer":[
        "Data Intelligence",
        "Root Cause Discovery",
        "Causal Discovery",
        "Causal Inference",
        "Counterfactual Intelligence",
        "Decision Intelligence"
    ],

    "Status":[
        "Implemented",
        "Implemented",
        "Implemented",
        "Implemented",
        "Implemented",
        "Implemented"
    ]

})

components

                         Layer       Status
0            Data Intelligence  Implemented
1         Root Cause Discovery  Implemented
2             Causal Discovery  Implemented
3             Causal Inference  Implemented
4  Counterfactual Intelligence  Implemented
5        Decision Intelligence  Implemented

In [29]:
components.to_csv(
    "../results/tables/adif_components.csv",
    index=False
)

In [33]:
print(report)

Based on the provided facts, I'll generate the requested outputs.

**Executive Summary**

Our analysis indicates that customer changes have the greatest impact on the business outcome, with an importance score of 0.535396. Conversely, order changes have the lowest impact, with a score of 0.117219. The average treatment effect is approximately 0.010647. We also found that increasing the impact by a certain percentage yields specific effects, ranging from 0.003097 (5% increase) to 0.030967 (50% increase).

**Key Findings**

1. Customer changes have the most significant impact on the business outcome, with an importance score of 0.535396.
2. The average treatment effect is approximately 0.010647.
3. Increasing the impact by a certain percentage yields specific effects:
	* A 5% increase results in an impact of 0.003097.
	* A 10% increase results in an impact of 0.006193.
	* A 20% increase results in an impact of 0.012387.
	* A 50% increase results in an impact of 0.030967.

**Strategic Recommendations**

1. **Prioritize efforts to address customer changes**: Given the high importance score (0.535396), it is essential to focus on understanding and addressing the root causes of customer changes to maximize their positive effect.
2. **Investigate further analysis for Order Changes**: Although order changes have the lowest impact, we cannot determine if there are opportunities to increase their effectiveness without further analysis (Not available from current analysis).
3. **Targeted interventions for specific percentage increases in impact**:
	* Consider implementing a 5% increase in some areas where a small boost could have a significant effect (0.003097).
	* For larger impacts, aim for the 20% or 50% increase targets, which would yield effects of 0.012387 and 0.030967, respectively.

In [34]:
print(importance)

           Feature  Importance
0  Customer_Change    0.535396
1  Quantity_Change    0.347384
2     Order_Change    0.117219

In [36]:
features = [
    "Customer_Change",
    "Order_Change",
    "Quantity_Change"
]
print(features)

['Customer_Change', 'Order_Change', 'Quantity_Change']

In [39]:
import pandas as pd

print("="*60)
print("ROOT CAUSE RESULTS")
print("="*60)

try:
    importance = pd.read_csv("../results/tables/root_cause_importance.csv")
    print(importance)
except Exception as e:
    print("Root Cause File Error:", e)

print("\n" + "="*60)
print("MODEL PERFORMANCE")
print("="*60)

try:
    model_comp = pd.read_csv("../results/tables/model_comparison.csv")
    print(model_comp)
except Exception as e:
    print("Model Comparison Error:", e)

print("\n" + "="*60)
print("COUNTERFACTUAL RESULTS")
print("="*60)

try:
    sensitivity = pd.read_csv("../results/tables/sensitivity_analysis.csv")
    print(sensitivity)
except Exception as e:
    print("Sensitivity Error:", e)

print("\n" + "="*60)
print("FINAL RESULTS")
print("="*60)

try:
    final_results = pd.read_csv("../results/tables/final_results.csv")
    print(final_results)
except Exception as e:
    print("Final Results Error:", e)

print("\n" + "="*60)
print("FILES AVAILABLE")
print("="*60)

import os

print(os.listdir("../results/tables"))

============================================================
ROOT CAUSE RESULTS
============================================================
           Feature  Importance
0  Customer_Change    0.535396
1  Quantity_Change    0.347384
2     Order_Change    0.117219

============================================================
MODEL PERFORMANCE
============================================================
               Model    CV_R2
0  Linear Regression -12.4217
1      Random Forest  -0.1591
2            XGBoost   0.3604

============================================================
COUNTERFACTUAL RESULTS
============================================================
   Increase    Impact
0         5  0.003097
1        10  0.006193
2        20  0.012387
3        50  0.030967

============================================================
FINAL RESULTS
============================================================
         Metric         Value
0  Dataset Size  1.041670e+06
1     Customers  5.878000e+03
2      Products  4.917000e+03
3     Countries  4.300000e+01
4       Revenue  2.097259e+07
5      R2 Score  9.999940e-01
6          RMSE  6.850000e-04

============================================================
FILES AVAILABLE
============================================================
['adif_components.csv', 'final_results.csv', 'model_comparison.csv', 'recommendations.csv', 'root_cause_importance.csv', 'sensitivity_analysis.csv']

In [40]:
print("estimate" in globals())
print("identified_estimand" in globals())
print("causal_model" in globals())
print("causal_df" in globals())

False
False
False
False

In [41]:
try:
    print("ATE =", estimate.value)
except:
    print("ATE not loaded")

ATE not loaded